# Generated by Django 5.2.1 on 2025-09-30 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=15)),
                ('emlak_tipi', models.CharField(choices=[('satilik', 'Satılık'), ('kiralik', 'Kiralık'), ('gunluk_kiralik', 'Günlük Kiralık')], max_length=20)),
                ('kategori', models.CharField(choices=[('daire', 'Daire'), ('villa', 'Villa'), ('mustakil', 'Müstakil Ev'), ('residence', 'Residence'), ('arsa', 'Arsa'), ('isyeri', 'İş Yeri'), ('depo', 'Depo')], max_length=20)),
                ('metrekare', models.IntegerField()),
                ('oda_sayisi', models.CharField(max_length=20)),
                ('bina_yasi', models.IntegerField(blank=True, null=True)),
                ('kat', models.IntegerField(blank=True, null=True)),
                ('isitma', models.CharField(blank=True, max_length=50, null=True)),
                ('esya_durumu', models.BooleanField(default=False)),
                ('aidat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ilce', models.CharField(max_length=50)),
                ('mahalle', models.CharField(max_length=100)),
                ('adres', models.TextField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('aktif', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IlanResim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='ilan_resimleri/')),
                ('sira', models.IntegerField(default=0)),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resimler', to='ilanlar.ilan')),
            ],
            options={
                'ordering': ['sira'],
            },
        ),
        migrations.CreateModel(
            name='IlanFavori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilanlar.ilan')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('kullanici', 'ilan')},
            },
        ),
    ]
