# Generated by Django 5.2.1 on 2025-10-01 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='il',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ilce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilanlar.il')),
            ],
        ),
        migrations.AddField(
            model_name='ilan',
            name='il',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilanlar_il', to='ilanlar.ilce'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='ilce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilanlar_ilce', to='ilanlar.ilce'),
        ),
    ]
