# Generated by Django 5.2.1 on 2025-10-01 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0002_il_ilce_ilan_il_alter_ilan_ilce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='il',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilanlar_il', to='ilanlar.il'),
        ),
    ]
