# Generated by Django 5.2.1 on 2025-10-01 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0003_alter_ilan_il'),
    ]

    operations = [
        migrations.CreateModel(
            name='semt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilanlar.ilce')),
            ],
        ),
        migrations.AlterField(
            model_name='ilan',
            name='mahalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilanlar_mahalle', to='ilanlar.semt'),
        ),
    ]
