# Generated by Django 5.2.1 on 2025-10-01 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0004_semt_alter_ilan_mahalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='semt',
            name='il',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ilanlar.il'),
            preserve_default=False,
        ),
    ]
