# Generated by Django 5.2.1 on 2025-10-01 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0005_semt_il'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ilans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ilan',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ilan',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
